spring.application.name=smartbiz-backend

spring.datasource.url=jdbc:mysql://localhost:3306/smartbiz_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1988@Ara
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=YourSuperLongAndSecureSecretKeyThatIsAtLeast256BitsLongForHS256
jwt.expiration.ms=86400000
